apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensetracker-ui-deployment
  labels:
    app: expensetracker-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expensetracker-ui
  template:
    metadata:
      labels:
        app: expensetracker-ui
    spec:
      containers:
        - name: expensetracker-ui
          image: kalyankumar21/expensetracker-ui:3.0
          env:
            - name: REACT_APP_API_URL
              value: http://localhost:30007
          ports:
            - containerPort: 3000
