apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensetracker-api-deployment
  labels:
    app: expensetracker-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expensetracker-api
  template:
    metadata:
      labels:
        app: expensetracker-api
    spec:
      containers:
        - name: expensetracker-api
          image: kalyankumar21/expensetracker-api:3.0
          env:
            - name: DBURL
              value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/Expense-Tracker-db?replicaSet=rs0
          ports:
            - containerPort: 3001
