apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensetracker-ui-deployment
  # namespace: cloudchamp
  labels:
    app: expensetracker-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expensetracker-ui
  template:
    metadata:
      labels:
        app: expensetracker-ui
    spec:
      containers:
        - name: expensetracker-ui
          image: kalyankumar21/expensetracker-ui:3.0
          env:
            - name: REACT_APP_API_URL
              value: http://a1e93142c65454637b953c36631e1eab-1966761665.ap-south-1.elb.amazonaws.com
          ports:
            - containerPort: 3000
