apiVersion: v1
kind: Service
metadata:
  name: expensetracker-ui-service
spec:
  type: NodePort
  selector:
    app: expensetracker-ui
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30008
