apiVersion: v1
kind: Service
metadata:
  name: expensetracker-api-service
spec:
  type: LoadBalancer
  selector:
    app: expensetracker-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
