apiVersion: v1
kind: Service
metadata:
  name: expensetracker-ui-service
  # namespace: cloudchamp
spec:
  type: LoadBalancer
  selector:
    app: expensetracker-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
